// <auto-generated />
namespace Shopping_cart_dotnetmvc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class casss : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(casss));
        
        string IMigrationMetadata.Id
        {
            get { return "202211221602271_casss"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
