// <auto-generated />
namespace Shopping_cart_dotnetmvc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class cartsss : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cartsss));
        
        string IMigrationMetadata.Id
        {
            get { return "202211221208409_cartsss"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
